# SPDX-License-Identifier: GPL-2.0
# FPGA : BigOrca
dtb-$(CONFIG_PLAT_AE350) += a25_c1_d_dsp_noncoherent_ae350.dtb
dtb-$(CONFIG_PLAT_AE350) += a27l2_c1_d_dsp_noncoherent_ae350.dtb
dtb-$(CONFIG_PLAT_AE350) += a45_c1_d_dsp_noncoherent_ae350.dtb
dtb-$(CONFIG_PLAT_AE350) += ax25_c1_d_dsp_noncoherent_ae350.dtb
dtb-$(CONFIG_PLAT_AE350) += ax27l2_c1_d_dsp_noncoherent_ae350.dtb
dtb-$(CONFIG_PLAT_AE350) += ax45_c1_d_dsp_noncoherent_ae350.dtb

# FPGA : VCU118
dtb-$(CONFIG_PLAT_AE350) += a25mp_c4_d_dsp_ae350.dtb
dtb-$(CONFIG_PLAT_AE350) += a45mp_c4_d_dsp_ae350.dtb
dtb-$(CONFIG_PLAT_AE350) += ax25mp_c4_d_dsp_ae350.dtb
dtb-$(CONFIG_PLAT_AE350) += ax45mp_c4_d_dsp_ae350.dtb
dtb-$(CONFIG_PLAT_AE350) += ax45mp_c8_ae350.dtb

# FPGA : VU19P
dtb-$(CONFIG_PLAT_AE350) += ax65mp_c2_d_dsp_ae350.dtb
obj-$(CONFIG_BUILTIN_DTB) += $(addsuffix .o, $(dtb-y))
