# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2023 Andes Technology Corporation.

obj-y	+= andes_sbi.o pm.o
obj-y	+= inject_init.o
obj-$(CONFIG_ATCDMAC300)	+= atcdmac300.o dmad_intc.o
obj-$(CONFIG_ANDES_CACHE)	+= cache.o
obj-$(CONFIG_ANDES_DMA_NONCOHERENT)	+= dma-noncoherent.o
obj-$(CONFIG_ANDES_PPMA)	+= ppma.o
obj-$(CONFIG_ANDES_ATCSMU)	+= atcsmu.o
