# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2023 Andes Technology Corporation.

obj-y	+= andes_sbi.o
obj-y	+= inject_init.o
obj-$(CONFIG_ANDES_CACHE)		+= cache.o
obj-$(CONFIG_ANDES_DMA_NONCOHERENT)	+= dma-noncoherent.o
obj-$(CONFIG_ANDES_PPMA)		+= ppma.o

